version: '3.1'

services:
  app:
    build: .
    container_name: "http-car"
    image: "leandroyou/http-car"
    command: -m mongodb -r redis
    ports:
      - 8080:8080
    links:
      - mongodb
      - redis
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - /var/lib/boot2docker/my-mongodb-data/:/data/db/
    ports:
      - 27017:27017

  redis:
    image: redis:alpine
    container_name: "redis"
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ./dataRedis:/data

